### ISSUE TITLE
Библиотеки

### ISSUE THREAD

**Issue by Ardalin** [BigGeekBrain/GeekBrains-JavaScript#1]
Есть предложение и это правило хорошего тона, до того как пушить в гит внешние библиотеки типа **_node_modules_** или иногда папки типа **_vendor_** добавить в **_.gitignore_**

Потому как эти файлы не отражают сути нашей работы и в добавок захламляют место на наших компах. 

**Предложение** - разобраться как исключить эти папки из нашего общего репозитория.

**Comment by BigGeekBrain** [comment]
Хорошее предложение, на сколько я понял, мы задаем правило и не отправляем некоторые файлы на сервер github.

**Comment by Ardalin** [comment]
Да всё верно. В частности у Дамира в репе такая папка есть. Одна такая не страшно, но по факту она будет расти и множиться по мере развития, а значит и "раковая опухоль" в рамках наших компов.

**Comment by Damir92** [comment]
Я уже подчистил эту ситуацию, сделал все согласно заданию, где требовалось оставить только gulpfile.js и ничего лишнего!
